description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4.2.0
      with:
        version: 10.30.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.4.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm
    - run: pnpm install
      shell: bash
  using: composite